In [1]:
from thoughtsformer import ThoughtsFormer



import torch
from transformers import GPT2LMHeadModel, GPT2Tokenizer

model = ThoughtsFormer.from_pretrained_GPT2()

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

def generate(prompt, max_length=50):
    input_ids = tokenizer.encode(prompt, return_tensors='pt').to(device)
    for _ in range(max_length):
        with torch.no_grad():
            outputs = model.forward_ppo_with_tokens(input_ids, torch.zeros_like(input_ids),0)[0][:,-1,:]
            
        next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)
        input_ids = torch.cat([input_ids, next_token_id], dim=-1)
        print(tokenizer.decode(input_ids[0], skip_special_tokens=True))
        if next_token_id.item() == tokenizer.eos_token_id:
            break
        
generate("next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)")

c:\Users\bicke\anaconda3\envs\megatron\Lib\site-packages\torch\nn\modules\transformer.py:307: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
c:\Users\bicke\anaconda3\envs\megatron\Lib\site-packages\transformers\tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
c:\Users\bicke\anaconda3\envs\megatron\Lib\site-packages\torch\nn\functional.py:5560: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native

next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)


next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length >
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length > 0
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length > 0 then
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length > 0 then

next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length > 0 then


next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length > 0 then

output
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length > 0 then

outputs
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if

In [1]:
import torch
input = torch.load("test.pt", weights_only=True)

import torch
from transformers import GPT2LMHeadModel
from one_step_thoughtsformer import ThoughtsFormer, NewGELUActivation
# t = GPT2Tokenizer.from_pretrained("gpt2")
pret = GPT2LMHeadModel.from_pretrained("gpt2")
custom_model = ThoughtsFormer(num_layers=12,vocab_size=50257, d_embed = 768, dim_feedforward=768 * 4, n_head=12, max_context_length=1024, max_thought_len=0, dropout=0.15, activation=NewGELUActivation(), sinusoidal_position_encoding=False)


pdict = pret.state_dict()
cdict = custom_model.state_dict()
# sentence = "Once upon a time"
pdict = pret.state_dict()
cdict = custom_model.state_dict()

explicit_map = {
    'token_embedding.weight' : 'transformer.wte.weight',
    'policy_feedforward.weight' : 'lm_head.weight',
    'transformer.transformer.norm.weight' : 'transformer.ln_f.weight',
    'transformer.transformer.norm.bias' : 'transformer.ln_f.bias',
    'transformer.dual_positional_encoding.learned_positional_encoding.weight' : 'transformer.wpe.weight'
}

for k, v in explicit_map.items():
    assert cdict[k].shape == pdict[v].shape
    cdict[k].copy_(pdict[v])
    
for i in range(12):
    layer_explicit_map = {
        f"transformer.transformer.layers.{i}.linear1.weight" : f"transformer.h.{i}.mlp.c_fc.weight" ,
        f"transformer.transformer.layers.{i}.linear1.bias" : f"transformer.h.{i}.mlp.c_fc.bias" ,
        f"transformer.transformer.layers.{i}.linear2.weight" : f"transformer.h.{i}.mlp.c_proj.weight", 
        f"transformer.transformer.layers.{i}.linear2.bias" : f"transformer.h.{i}.mlp.c_proj.bias" ,
        f"transformer.transformer.layers.{i}.norm1.weight" : f"transformer.h.{i}.ln_1.weight", 
        f"transformer.transformer.layers.{i}.norm1.bias" : f"transformer.h.{i}.ln_1.bias", 
        f"transformer.transformer.layers.{i}.norm2.weight" : f"transformer.h.{i}.ln_2.weight", 
        f"transformer.transformer.layers.{i}.norm2.bias" : f"transformer.h.{i}.ln_2.bias", 
        f"transformer.transformer.layers.{i}.self_attn.out_proj.weight" : f"transformer.h.{i}.attn.c_proj.weight", 
        f"transformer.transformer.layers.{i}.self_attn.out_proj.bias" : f"transformer.h.{i}.attn.c_proj.bias",
        f"transformer.transformer.layers.{i}.self_attn.in_proj_weight":  f"transformer.h.{i}.attn.c_attn.weight",
        f"transformer.transformer.layers.{i}.self_attn.in_proj_bias" : f"transformer.h.{i}.attn.c_attn.bias"
    }
    
    transposed = ['attn.c_attn.weight', 'attn.c_proj.weight', 'mlp.c_fc.weight', 'mlp.c_proj.weight']
    for k, v in layer_explicit_map.items():
        
        if any(v.endswith(w) for w in transposed):
            assert pdict[v].shape[::-1] == cdict[k].shape
            with torch.no_grad():
                cdict[k].copy_(pdict[v].t())
        else:
            # print(cdict[k].shape, pdict[v].shape, k, v)
            with torch.no_grad():
                assert cdict[k].shape == pdict[v].shape
                cdict[k].copy_(pdict[v])
    
custom_model.load_state_dict(cdict)
# cdict['token_embedding.weight'].shape
# cdict['transformer.transformer.layers.0.linear2.weight'].shape

sentence = "once upon a time"


from bpe import BPETokenizer
tokenizer = BPETokenizer()

torch.manual_seed(42)
# with torch.no_grad():
#     tokens = torch.tensor(tokenizer(sentence)).view(1,-1)
#     custom_model.eval()
#     predictions = custom_model.forward_ppo_with_tokens(tokens, torch.zeros_like(tokens),0)[0]
  
#     print(custom_model.transformer.transformer.layers[0](input))
    
    
#     print(custom_model.transformer.transformer.layers[0](input))

# x = predictions.argmax(dim=-1)
# tokenizer.decode(x[0])
# print("\n\nDesired Output")
# print(pret(tokens,output_hidden_states=True).hidden_states[1])


# Desired Output
# tensor([[[ 0.3191,  0.6466,  1.1327,  ..., -0.0743,  0.7379, -0.3372],
#          [-0.3657, -0.3845, -0.2498,  ..., -0.0071,  0.2876,  0.2585],
#          [-1.4182,  0.1991, -0.4063,  ...,  0.0237,  0.1473, -0.4916],
#          [ 0.2380, -0.8441, -0.0074,  ...,  0.6175, -0.6014,  0.4939]]],
#        grad_fn=<AddBackward0>)



self.disable_thought_encoding:  True


c:\Users\bicke\anaconda3\envs\megatron\Lib\site-packages\torch\nn\modules\transformer.py:307: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")


In [13]:
print("hi")
print("hi")
print("hi")
print("hi")

hi
hi
hi
hi


In [ ]:
# Desired Output
# tensor([[[ 0.3191,  0.6466,  1.1327,  ..., -0.0743,  0.7379, -0.3372],
#          [-0.3657, -0.3845, -0.2498,  ..., -0.0071,  0.2876,  0.2585],
#          [-1.4182,  0.1991, -0.4063,  ...,  0.0237,  0.1473, -0.4916],
#          [ 0.2380, -0.8441, -0.0074,  ...,  0.6175, -0.6014,  0.4939]]],
#        grad_fn=<AddBackward0>)

In [3]:
from transformers.models.gpt2.modeling_gpt2 import GPT2Block
desired_layer: GPT2Block = pret.transformer.h[0].to("cpu")
print(input.shape)
desired_layer.forward(input.to("cpu"))

torch.Size([1, 1024, 768])


(tensor([[[ 2.2619, -0.7038,  1.1560,  ..., -0.7938,  0.8593, -1.1736],
          [ 0.7986, -1.2712,  0.3632,  ...,  0.3620,  1.5317, -2.4150],
          [ 2.6520,  2.7002, -1.5714,  ..., -0.5710,  0.2848, -1.4666],
          ...,
          [ 0.2420,  0.1363, -0.1294,  ..., -0.8941, -1.0109, -0.3575],
          [ 0.2408,  0.1860, -0.1360,  ..., -0.8679, -1.0096, -0.3522],
          [ 0.0075, -0.0149, -0.1759,  ..., -0.5826, -0.4573, -0.2208]]],
        grad_fn=<AddBackward0>),
 None)

In [4]:
import torch
import torch.nn as nn
encoder_layer: nn.TransformerEncoderLayer = custom_model.transformer.transformer.layers[0]
mask = torch.zeros_like(input[:,:,0]).bool()
encoder_layer.eval()
encoder_layer.forward(input.to("cpu"), src_mask=mask, is_causal=True)

# import torch.nn as nn
# encoder_layer: nn.TransformerEncoderLayer = custom_model.transformer.transformer.layers[0]
# mask = torch.zeros_like(input[:,:,0]).bool()
# mask[0,-1] = True
# mask[0,-2] = True
# mask[0,-3] = True

# after:  tensor([[[ 0.0275,  0.0141, -0.0031,  ...,  0.5349,  0.2867,  0.1896],
#          [ 0.0340,  0.1176,  0.0336,  ...,  1.1702,  0.1436,  0.4704],
#          [ 0.0355,  0.1407,  0.0450,  ...,  1.1279,  0.0273,  0.4527],
#          ...,
#          [-0.0236,  0.0494,  0.1736,  ..., -0.4440, -1.1006, -0.5862],
#          [-0.0308,  0.0440,  0.1965,  ..., -0.6584, -1.1000, -0.5023],
#          [ 0.0411,  0.1527, -0.0938,  ...,  0.5289,  0.0380,  0.5038]]]



tensor([[[ 2.2614, -0.7036,  1.1556,  ..., -0.7940,  0.8593, -1.1735],
         [ 0.7983, -1.2712,  0.3622,  ...,  0.3625,  1.5325, -2.4162],
         [ 2.6506,  2.7003, -1.5726,  ..., -0.5697,  0.2851, -1.4677],
         ...,
         [ 0.2421,  0.1367, -0.1292,  ..., -0.8943, -1.0112, -0.3574],
         [ 0.2412,  0.1864, -0.1357,  ..., -0.8680, -1.0098, -0.3523],
         [-0.2108,  0.1408, -0.1659,  ..., -0.6663, -0.4568, -0.2405]]],
       grad_fn=<WhereBackward0>)

In [5]:
input = torch.load("test.pt")
print(input)

tensor([[[-1.3011e-01, -3.1431e-01,  1.6472e-01,  ...,  1.2347e-01,
           1.3407e-01,  8.7543e-02],
         [ 1.6650e-02, -1.4323e-01, -9.4386e-02,  ..., -2.1990e-02,
           1.2575e-01, -3.5732e-02],
         [ 1.9453e-01, -9.8574e-02,  1.7581e-01,  ..., -5.6061e-02,
          -3.9454e-02, -1.2669e-01],
         ...,
         [-1.7987e-03,  1.6052e-03, -5.5103e-02,  ...,  1.3617e-02,
          -7.1805e-03,  3.7552e-03],
         [ 3.2105e-03,  1.5501e-03, -4.8944e-02,  ...,  2.0725e-02,
          -1.1838e-02, -5.5683e-04],
         [ 2.6610e-04,  3.0272e-03, -1.7086e-03,  ..., -4.6506e-03,
          -2.3541e-03, -5.7855e-03]]], device='cuda:0')


C:\Users\bicke\AppData\Local\Temp\ipykernel_75672\3038415613.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  input = torch.load("test.pt")


In [11]:
print("hi")
print("hi")
print("hi")
print("hi")
print("hi")

hi
hi
hi
hi
hi


In [30]:
def get_weight(d, name):
        """Retrieve weights from the appropriate dictionary."""
        return d[name]
print(get_weight(cdict, f"transformer.transformer.layers.{0}.self_attn.out_proj.weight"))
print(get_weight(pdict, f"transformer.h.{0}.attn.c_proj.weight"))

tensor([[ 0.3127, -0.2442, -0.4301,  ...,  0.0202,  0.0171, -0.1011],
        [-0.1874, -0.1978,  0.1544,  ...,  0.1984,  0.0252, -0.0735],
        [ 0.0980, -0.1098,  0.0538,  ..., -0.1482, -0.0184, -0.0024],
        ...,
        [-0.0120, -0.0162,  0.0143,  ...,  0.0235, -0.0008,  0.0063],
        [ 0.0094,  0.0250, -0.0181,  ...,  0.0107,  0.0086,  0.0132],
        [-0.0309,  0.0459, -0.0016,  ..., -0.0150,  0.0050, -0.0171]])
tensor([[ 0.3127, -0.1874,  0.0980,  ..., -0.0120,  0.0094, -0.0309],
        [-0.2442, -0.1978, -0.1098,  ..., -0.0162,  0.0250,  0.0459],
        [-0.4301,  0.1544,  0.0538,  ...,  0.0143, -0.0181, -0.0016],
        ...,
        [ 0.0202,  0.1984, -0.1482,  ...,  0.0235,  0.0107, -0.0150],
        [ 0.0171,  0.0252, -0.0184,  ..., -0.0008,  0.0086,  0.0050],
        [-0.1011, -0.0735, -0.0024,  ...,  0.0063,  0.0132, -0.0171]])


In [2]:
#already loaded in 
custom_model.load_state_dict(cdict)

pdict2 = pret.state_dict()
cdict2 = custom_model.state_dict()
# print(pdict2["transformer.h.0.attn.c_attn.weight"].shape)
print(cdict2["transformer.transformer.layers.0.self_attn.in_proj_weight"].shape)
# if False:
i = 0 
layer_explicit_map = {
        f"transformer.transformer.layers.{i}.linear1.weight" : f"transformer.h.{i}.mlp.c_fc.weight" ,
        f"transformer.transformer.layers.{i}.linear1.bias" : f"transformer.h.{i}.mlp.c_fc.bias" ,
        f"transformer.transformer.layers.{i}.linear2.weight" : f"transformer.h.{i}.mlp.c_proj.weight", 
        f"transformer.transformer.layers.{i}.linear2.bias" : f"transformer.h.{i}.mlp.c_proj.bias" ,
        f"transformer.transformer.layers.{i}.norm1.weight" : f"transformer.h.{i}.ln_1.weight", 
        f"transformer.transformer.layers.{i}.norm1.bias" : f"transformer.h.{i}.ln_1.bias", 
        f"transformer.transformer.layers.{i}.norm2.weight" : f"transformer.h.{i}.ln_2.weight", 
        f"transformer.transformer.layers.{i}.norm2.bias" : f"transformer.h.{i}.ln_2.bias", 
        f"transformer.transformer.layers.{i}.self_attn.out_proj.weight" : f"transformer.h.{i}.attn.c_proj.weight", 
        f"transformer.transformer.layers.{i}.self_attn.out_proj.bias" : f"transformer.h.{i}.attn.c_proj.bias",
        f"transformer.transformer.layers.{i}.self_attn.in_proj_weight":  f"transformer.h.{i}.attn.c_attn.weight",
        f"transformer.transformer.layers.{i}.self_attn.in_proj_bias" : f"transformer.h.{i}.attn.c_attn.bias"
    }

# for k,v in layer_explicit_map.items():
#     print(k, " : ", v)
#     if (cdict2[k].ndim == 2):
#         print(cdict2[k][0:2, 0:2], "\n",pdict2[v][0:2, 0:2])
#     else:
#         print(cdict2[k][0:2], "\n",pdict2[v][0:2])
#     print("----")

from bpe import BPETokenizer

tokenizer = BPETokenizer()

x = tokenizer("Once upon a time")
y = custom_model.forward_ppo_with_tokens(x, torch.zeros_like(x),0)

torch.Size([2304, 768])


In [139]:
out = torch.topk(y[0][:,-1,:], k = 5, dim=-1).indices.flatten()

In [140]:
tokenizer.decode(out)

' exha loophsenal�士ortium'

In [3]:
import torch
from transformers import GPT2LMHeadModel, GPT2Tokenizer

model = custom_model
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

def generate(prompt, max_length=50):
    input_ids = tokenizer.encode(prompt, return_tensors='pt').to(device)
    for _ in range(max_length):
        with torch.no_grad():
            outputs = model.forward_ppo_with_tokens(input_ids, torch.zeros_like(input_ids),0)[0][:,-1,:]
            
        next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)
        input_ids = torch.cat([input_ids, next_token_id], dim=-1)
        print(tokenizer.decode(input_ids[0], skip_special_tokens=True))
        if next_token_id.item() == tokenizer.eos_token_id:
            break
        
generate("next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)")

c:\Users\bicke\anaconda3\envs\megatron\Lib\site-packages\transformers\tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
c:\Users\bicke\anaconda3\envs\megatron\Lib\site-packages\torch\nn\functional.py:5560: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)


next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)


next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length >
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length > 0
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length > 0 then
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length > 0 then

next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length > 0 then


next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length > 0 then

output
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if outputs.length > 0 then

outputs
next_token_id = outputs.argmax(dim=-1).unsqueeze(-1)

if

In [27]:
input_ids

NameError: name 'input_ids' is not defined

In [63]:
cdict.keys()

odict_keys(['transformer.dual_positional_encoding.learned_positional_encoding.weight', 'transformer.dual_positional_encoding.position_in_thought_encoding.weight', 'transformer.transformer.layers.0.self_attn.in_proj_weight', 'transformer.transformer.layers.0.self_attn.in_proj_bias', 'transformer.transformer.layers.0.self_attn.out_proj.weight', 'transformer.transformer.layers.0.self_attn.out_proj.bias', 'transformer.transformer.layers.0.linear1.weight', 'transformer.transformer.layers.0.linear1.bias', 'transformer.transformer.layers.0.linear2.weight', 'transformer.transformer.layers.0.linear2.bias', 'transformer.transformer.layers.0.norm1.weight', 'transformer.transformer.layers.0.norm1.bias', 'transformer.transformer.layers.0.norm2.weight', 'transformer.transformer.layers.0.norm2.bias', 'transformer.transformer.layers.1.self_attn.in_proj_weight', 'transformer.transformer.layers.1.self_attn.in_proj_bias', 'transformer.transformer.layers.1.self_attn.out_proj.weight', 'transformer.transfor

In [52]:
cdict['transformer.wte.weight']

tensor([[-0.1101, -0.0393,  0.0331,  ..., -0.1364,  0.0151,  0.0453],
        [ 0.0403, -0.0486,  0.0462,  ...,  0.0861,  0.0025,  0.0432],
        [-0.1275,  0.0479,  0.1841,  ...,  0.0899, -0.1297, -0.0879],
        ...,
        [-0.0445, -0.0548,  0.0123,  ...,  0.1044,  0.0978, -0.0695],
        [ 0.1860,  0.0167,  0.0461,  ..., -0.0963,  0.0785, -0.0225],
        [ 0.0514, -0.0277,  0.0499,  ...,  0.0070,  0.1552,  0.1207]])

13

In [5]:
predictions = custom_model.forward_ppo_with_tokens(tokens, torch.zeros_like(tokens),0)[0]
x = predictions.argmax(dim=-1)
t.decode(x[0])

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)

In [33]:
tokens.bool().dtype == torch.int64

False

Number of attention heads: 12


In [3]:
import torch
from transformers import GPT2Tokenizer

def predict_next_token(model: ThoughtsFormer, tokenizer, sentence, device):
    # Tokenize the input sentence
    input_ids = tokenizer.encode(sentence, return_tensors='pt').to(device)
    
    # Generate attention mask
    attention_mask = torch.zeros_like(input_ids).to(device).bool()
    
    # Get the model's prediction
    with torch.no_grad():
        outputs = model.forward_ppo_with_tokens(input_ids, attention_mask, 0)
        logits = outputs.logits if hasattr(outputs, 'logits') else outputs[0]
    
    # Get the predictions for the last token
    next_token_logits = logits[0, -1, :]
    
    # Get the top 5 candidates
    top_5_tokens = torch.topk(next_token_logits, 5, dim=-1)
    
    return top_5_tokens.indices, top_5_tokens.values

# Set up the model and tokenizer
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = ThoughtsFormer(vocab_size=50257, d_embed=768, dim_feed_forward=768 * 4, n_head=12, max_context_length=1024, thought_length=0, sinusoidal_position_encoding=False).to(device)

# Load your trained weights
model = custom_model.to(device)
model.eval()

# Test sentence
test_sentence = "The quick brown fox jumps over the lazy"

# Predict next token
top_indices, top_scores = predict_next_token(model, tokenizer, test_sentence, device)

# Print results
print(f"Input: {test_sentence}")
print("Top 5 predicted next tokens:")
for i, (index, score) in enumerate(zip(top_indices, top_scores), 1):
    token = tokenizer.decode([index])
    print(f"{i}. '{token}' (score: {score.item():.4f})")

c:\Users\bicke\anaconda3\envs\megatron\Lib\site-packages\torch\nn\modules\transformer.py:720: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  return torch._transformer_encoder_layer_fwd(


Input: The quick brown fox jumps over the lazy
Top 5 predicted next tokens:
1. ' looph' (score: 14.0095)
2. ' exha' (score: 12.0068)
3. '�士' (score: 11.4057)
4. ' tremend' (score: 9.3803)
5. ' millenn' (score: 9.2363)


In [34]:

# Method 2: Save only the state dictionary (recommended)
torch.save(custom_model.state_dict(), 'gpt2_starting_thoughtsformer.pth')